# .github/labeler.yml
backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"

frontend:
  - changed-files:
      - any-glob-to-any-file: "mobile/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile*"
          - "docker-compose*.yml"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

database:
  - changed-files:
      - any-glob-to-any-file:
          - "backend/alembic/**"
          - "backend/app/models/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/test_*.py"
          - "**/*_test.py"
          - "**/tests/**"
          - "mobile/test/**"
