coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
      backend:
        target: 85%
        flags:
          - backend
      frontend:
        target: 75%
        flags:
          - frontend
    patch:
      default:
        target: 80%

flags:
  backend:
    paths:
      - backend/
    carryforward: true
  frontend:
    paths:
      - mobile/
    carryforward: true

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*_test.py"
  - "**/test_*.py"
  - "**/*.g.dart"
  - "**/migrations/**"
  - "mobile/test/**"
  - "backend/tests/**"
