name: 🐛 Bug Report
description: Report something that isn't working right
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue!
        We know filling out forms can be tough with ADHD, so we've kept this simple.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear, concise description of the bug
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: What should have happened instead?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Which part of NQI?
      options:
        - Quest Board
        - Epic Management
        - Sync Issues
        - Mobile App
        - API/Backend
        - Other
    validations:
      required: true
