name: Pull Request Management

on:
  pull_request:
    types: [opened, closed]

jobs:
  manage-pull-requests:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read

    steps:
      - name: Add labels to new PRs
        if: github.event.action == 'opened'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            try {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['in-review']
              });
              console.log('Successfully added in-review label');
            } catch (error) {
              console.error('Failed to add labels:', error.message);
              throw error;
            }

      - name: Handle merged PRs
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            try {
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['completed']
              });
              console.log('Successfully added completed label to merged PR');
            } catch (error) {
              console.error('Failed to add completed label:', error.message);
              throw error;
            }

      - name: Handle closed but not merged PRs
        if: github.event.action == 'closed' && github.event.pull_request.merged == false
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            console.log('PR was closed without merging - no action required');
