name: Pull Request Management

on:
  pull_request:
    types: [opened, closed]

jobs:
  manage-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Add new PR to In Review
        if: github.event.action == 'opened'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/${{ github.repository_owner }}/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move merged PR to Done and add completed label
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/github-script@v7
        with:
          script: |
            // Add completed label to merged PR
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['completed']
            });

            // Move to Done column in project board
            // Note: This requires the project board to be configured with automation
            // or additional API calls to move items between columns
            console.log('PR merged and labeled as completed');

      - name: Handle closed but not merged PR
        if: github.event.action == 'closed' && github.event.pull_request.merged == false
        uses: actions/github-script@v7
        with:
          script: |
            console.log('PR was closed without merging - no additional action required');
            // Optionally add a label for closed-without-merge PRs
            // await github.rest.issues.addLabels({
            //   issue_number: context.issue.number,
            //   owner: context.repo.owner,
            //   repo: context.repo.repo,
            //   labels: ['closed-without-merge']
            // });
